#!/bin/bash

here=`echo $0 | sed -e 's/\/'$(basename $0)'$//'`; if [ "$here" = "`basename $0`" ]; then here="`pwd`"; fi
. /home/native/.profile
GAMES=/mmc/mmca1/games
export HOME=$here
mkdir -p /mmc/mmca1/games/logs

if [ -f $GAMES/gamesrc ]; then
   . $GAMES/gamesrc
else
   export LD_LIBRARY_PATH=$GAMES/lib:$LD_LIBRARY_PATH
   #export SDL_QT_INVERT_ROTATION=1
fi

ulimit -c unlimited

cd $here
if [ ! -f "$here/scalar.ezx" ]; then
	echo "ERROR: The application binary is missing!" #> /mmc/mmca1/games/logs/scalar.ezx.log 2>&1
	exit 1
fi
if [ "$1" = "gdb" ]; then
	if [ "$2" != "" ]; then exec $GAMES/bin/gdb scalar.ezx $2;
	else exec $GAMES/bin/gdb scalar.ezx core; fi
elif [ "$1" = "strace" ]; then
	exec $GAMES/bin/strace $here/run
else
	exec $here/scalar.ezx #> /mmc/mmca1/games/logs/scalar.ezx.log 2>&1
fi
