#!/bin/bash

. /home/native/.profile

here=`echo $0 | sed -e 's/\/'$(basename $0)'$//'`; if [ "$here" = "`basename $0`" ]; then here="`pwd`"; fi
GAMES=/mmc/mmca1/games
appname=2h4u.ezx
export HOME=$here
mkdir -p $GAMES/logs

if [ -f $GAMES/gamesrc ]; then
   . $GAMES/gamesrc
else
   export LD_LIBRARY_PATH=$here/lib:$GAMES/lib:$LD_LIBRARY_PATH
   #export SDL_QT_INVERT_ROTATION=1
fi

cd $here
if [ ! -f "$here/$appname" ]; then
	echo "ERROR: The application binary is missing!" > $GAMES/logs/$appname.log 2>&1
	exit 1
fi

exec $here/$appname > $GAMES/logs/$appname.log 2>&1

