#!/bin/bash

here=`echo $0 | sed -e 's/\/'$(basename $0)'$//'`; if [ "$here" = "`basename $0`" ]; then here="`pwd`"; fi
. /home/native/.profile
GAMES=/mmc/mmca1/games
export HOME=$here
appname='snake.ezx'

if [ -f $GAMES/gamesrc ]; then
   . $GAMES/gamesrc
else
   export LD_LIBRARY_PATH=$GAMES/lib:$LD_LIBRARY_PATH
fi
   export SDL_QT_INVERT_ROTATION=1	#  0 for playing with left hand

cd $here
if [ ! -f "$here/$appname" ]; then
	echo "ERROR: The application binary is missing!" > /mmc/mmca1/games/logs/$appname.log 2>&1
	exit 1
fi

	exec $here/$appname > /mmc/mmca1/games/logs/$appname.log 2>&1
